services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_WSS_URL: ${NEXT_PUBLIC_WSS_URL}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_AUTH_API_URL: ${NEXT_PUBLIC_AUTH_API_URL}
        NEXT_PUBLIC_AUTH_URL: ${NEXT_PUBLIC_AUTH_URL}
    ports:
      - 3003:3003
    env_file:
      - .env
  
  db:
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
      POSTGRES_DB: chauffagistes
    ports:
      - "${POSTGRE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRE_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
